test

diff --git a/.github/workflows/api-cicd.yml b/.github/workflows/api-cicd.yml
--- a/.github/workflows/api-cicd.yml
+++ b/.github/workflows/api-cicd.yml
@@ -43,29 +43,38 @@ jobs:
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wastefree-api:latest
 
-      - name: Add known hosts
-        run: |
-          set -e
-          HOST='${{ secrets.DEPLOY_HOST }}'
-          if [ -z "$HOST" ]; then
-            echo "ERROR: Secret DEPLOY_HOST nie jest ustawiony." >&2
-            exit 1
-          fi
-          mkdir -p ~/.ssh
-          # Próba pobrania kilku typów kluczy; ignoruj stderr (GitHub maskuje)
-          for t in ed25519 rsa ecdsa; do
-            ssh-keyscan -T 10 -p "$PORT" -t $t -H "$HOST" 2>/dev/null >> ~/.ssh/known_hosts || true
-          done
-          # Sprawdź czy coś faktycznie dodano
-          if ! grep -q "$HOST" ~/.ssh/known_hosts; then
-            echo "ERROR: Nie udało się pobrać klucza hosta dla $HOST." >&2
-            exit 1
-          fi
-
-      - name: Start ssh agent
-        uses: webfactory/ssh-agent@v0.9.0
+      - name: Execute remote SSH commands using password
+        uses: appleboy/ssh-action@v1
         with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+          host: ${{ secrets.DEPLOY_HOST }}
+          username: ${{ secrets.DEPLOY_USER }}
+          password: ${{ secrets.DEPLOY_PASSWORD }}
+          port: ${{ secrets.DEPLOY_PORT }}
+          script: whoami
+
+      # - name: Add known hosts
+      #   run: |
+      #     set -e
+      #     HOST='${{ secrets.DEPLOY_HOST }}'
+      #     if [ -z "$HOST" ]; then
+      #       echo "ERROR: Secret DEPLOY_HOST nie jest ustawiony." >&2
+      #       exit 1
+      #     fi
+      #     mkdir -p ~/.ssh
+      #     # Próba pobrania kilku typów kluczy; ignoruj stderr (GitHub maskuje)
+      #     for t in ed25519 rsa ecdsa; do
+      #       ssh-keyscan -T 10 -p "$PORT" -t $t -H "$HOST" 2>/dev/null >> ~/.ssh/known_hosts || true
+      #     done
+      #     # Sprawdź czy coś faktycznie dodano
+      #     if ! grep -q "$HOST" ~/.ssh/known_hosts; then
+      #       echo "ERROR: Nie udało się pobrać klucza hosta dla $HOST." >&2
+      #       exit 1
+      #     fi
+
+      # - name: Start ssh agent
+      #   uses: webfactory/ssh-agent@v0.9.0
+      #   with:
+      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
       - name: Deploy API on remote host
         env:
